version: "3.3"

networks:
  liver_default:
    external: true

services:
  cloudflaretunnel:
    container_name: tunnel-stream-02
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - liver_default
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
    container_name: rtmp_server
    volumes:
      - ./mfortn:/tmp/hls

  auth:
    build: ./auth
    container_name: auth_server